# Generated by Django 5.2.7 on 2025-10-03 18:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок задачи')),
                ('condition', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Условие задачи')),
                ('solution', models.CharField(max_length=200, verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
