# Generated by Django 5.2.7 on 2025-10-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_task_delete_tasks'),
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Test.test', verbose_name='Привязанный тест'),
            preserve_default=False,
        ),
    ]
