# Generated by Django 5.2.7 on 2025-10-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_article_test'),
        ('Test', '0003_alter_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Test.test', verbose_name='Привязанный тест'),
        ),
    ]
