# Generated by Django 5.2.7 on 2025-10-08 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='tests/%Y/%m/%d/', verbose_name='Изображение')),
                ('is_random', models.BooleanField(default=False, verbose_name='Перемешать?')),
                ('amount', models.IntegerField(default=10, help_text='Если вопросов привязанных к тесту больше чем указано в поле "Количество вопросов", то система случайным образом выберет указанное количество вопросов.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Количество вопросов')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['id'],
            },
        ),
    ]
