# Generated by Django 5.2.7 on 2025-10-08 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('photo', models.ImageField(upload_to='question_images/full_test/%Y/%m/%d')),
                ('answer1', models.CharField(blank=True, max_length=500, verbose_name='Ответ 1')),
                ('answer2', models.CharField(blank=True, max_length=500, verbose_name='Ответ 2')),
                ('answer3', models.CharField(blank=True, max_length=500, verbose_name='Ответ 3')),
                ('answer4', models.CharField(blank=True, max_length=500, verbose_name='Ответ 4')),
                ('right_answer', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Правильный ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test', verbose_name='Входит в тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
    ]
