# Generated by Django 5.2.7 on 2025-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='question_images/full_test/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
