# Generated by Django 5.2.7 on 2025-10-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
