# Generated by Django 5.2.7 on 2025-10-09 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0002_delete_profile'),
        ('Test', '0003_alter_question_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rightAnswers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Правильные ответы')),
                ('wrongAnswers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Неправильные ответы')),
                ('questions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего вопросов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Test.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['-created_at', '-test'],
            },
        ),
    ]
